### ISSUE TITLE
clone的地址有问题，麻烦更改下

### ISSUE THREAD

**Issue by 493Arceus** [WincerChan/Meme-generator#1]
https://github.com/WincerChan/Meme-generator.git

**Comment by WincerChan** [comment]
@493Arceus 报错为：`Permission denied (publickey).` ？
如果是的话表示需要为 github 添加 ssh key，否则只能使用 https 协议。

**Comment by 493Arceus** [comment]
git clone的时候报错

**Comment by lvzhanhe** [comment]
@493Arceus 我这里测试没有问题

**Comment by WincerChan** [comment]
@493Arceus 你需要把 ssh 公钥上传至 GitHub 才能使用 git 协议，具体步骤请参考[这里](https://help.github.com/articles/connecting-to-github-with-ssh/)
