### ISSUE TITLE
求助帖

### ISSUE THREAD

**Issue by TakeExplore** [WincerChan/Meme-generator#2]
带佬 想问问您关于博客配置的问题 T.T 真的很喜欢这个主题 但是不会配置 请问怎么联系呀 求救

**Comment by WincerChan** [comment]
...你想问我博客的配置可以在我的博客的 repo 里问啊，怎么跑到这里来问

**Comment by TakeExplore** [comment]
> ...你想问我博客的配置可以在我的博客的 repo 里问啊，怎么跑到这里来问

sorry..搞错了 想删掉 然后没找到在哪里删呢 0.0 打扰了

**Comment by WincerChan** [comment]
> > ...你想问我博客的配置可以在我的博客的 repo 里问啊，怎么跑到这里来问
> 
> sorry..搞错了 想删掉 然后没找到在哪里删呢 0.0 打扰了

https://github.com/WincerChan/MyBlog 这是我博客的 repo，配置都写在里面了
