### ISSUE TITLE
执行gatsby build报错

### ISSUE THREAD

**Issue by hungryfoolou** [WincerChan/Meme-generator#3]
我在执行gatsby build报错了，在网上也没有查到解决办法，想咨询下各位如何解决这个问题。
错误如下：
`[root@VM_0_15_centos Meme-generator]# gatsby build
success open and validate gatsby-configs — 0.006 s
success load plugins — 0.221 s
error Plugin gatsby-transformer-sharp returned an error

  Error: Could not locate the bindings file. Tried:
   → /opt/github_program/Meme-generator/node_modules/sharp/build/sharp.node
   → /opt/github_program/Meme-generator/node_modules/sharp/build/Debug/sharp.node
   → /opt/github_program/Meme-generator/node_modules/sharp/build/Release/sharp.node
   → /opt/github_program/Meme-generator/node_modules/sharp/out/Debug/sharp.node
   → /opt/github_program/Meme-generator/node_modules/sharp/Debug/sharp.node
   → /opt/github_program/Meme-generator/node_modules/sharp/out/Release/sharp.node
   → /opt/github_program/Meme-generator/node_modules/sharp/Release/sharp.node
   → /opt/github_program/Meme-generator/node_modules/sharp/build/default/sharp.node
   → /opt/github_program/Meme-generator/node_modules/sharp/compiled/8.9.0/linux/ia32/sharp.node
`

**Comment by WincerChan** [comment]
1. 你电脑依赖管理是 Yarn 还是 NPM
2. Node 版本是多少

参考：
https://github.com/gatsbyjs/gatsby/issues/9511
https://github.com/gatsbyjs/gatsby/issues/8488
https://github.com/nodejs/node-gyp/issues/1511
